spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authorization-1
    username: postgres
    password: Thirumal
server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://thirumal:thirumal@localhost:8762/eureka/
google:
  recaptcha:
    key:
      site: 6LcTncEkAAAAACymEdK_QG-
      secret: 6LcTncEkAAAAAOmE5T
      threshold: 0.5
notification: 
  enabled: true
  email:
    sender: no-reply@gamil.com
  sms: 
    sender: THIRU